UI_SHOW_MESSAGE = "UI_SHOW_MESSAGE"

UI_SHOW_ERROR = "UI_SHOW_ERROR"

UI_SHOW_STATUS = "UI_SHOW_STATUS"


REQUEST_PLAYER_MOVE = "REQUEST_PLAYER_MOVE"   # Presenter -> View

REQUEST_PLAYER_CHOICE = "REQUEST_PLAYER_CHOICE" # Presenter -> View

PLAYER_CHOICE_MADE = "PLAYER_CHOICE_MADE"       # View -> Presenter

# --- Data Events (Model -> Presenter) ---
DATA_PARTY_BASE_PLACED = "DATA_PARTY_BASE_PLACED"

# --- Game Flow Events (Model -> Presenter) ---
SETUP_PHASE_COMPLETE = "SETUP_PHASE_COMPLETE"